// Generated by https://www.skeleton.dev/docs/generator

import type { CustomThemeConfig } from "@skeletonlabs/tw-plugin";

export const customTheme: CustomThemeConfig = {
	name: "custom",
	properties: {
		// =~= Theme Properties =~=
		"--theme-font-family-base": '"Inter Variable", sans-serif',
		"--theme-font-family-heading": '"Inter Variable", sans-serif',
		"--theme-font-color-base": "0 0 0",
		"--theme-font-color-dark": "255 255 255",
		"--theme-rounded-base": "8px",
		"--theme-rounded-container": "8px",
		"--theme-border-base": "1px",
		// =~= Theme On-X Colors =~=
		"--on-primary": "0 0 0",
		"--on-secondary": "255 255 255",
		"--on-tertiary": "0 0 0",
		"--on-success": "0 0 0",
		"--on-warning": "0 0 0",
		"--on-error": "255 255 255",
		"--on-surface": "255 255 255",
		// =~= Theme Colors  =~=
		// primary | #7f9fff
		"--color-primary-50": "236 241 255", // #ecf1ff
		"--color-primary-100": "229 236 255", // #e5ecff
		"--color-primary-200": "223 231 255", // #dfe7ff
		"--color-primary-300": "204 217 255", // #ccd9ff
		"--color-primary-400": "165 188 255", // #a5bcff
		"--color-primary-500": "127 159 255", // #7f9fff
		"--color-primary-600": "114 143 230", // #728fe6
		"--color-primary-700": "95 119 191", // #5f77bf
		"--color-primary-800": "76 95 153", // #4c5f99
		"--color-primary-900": "62 78 125", // #3e4e7d
		// secondary | #4747cc
		"--color-secondary-50": "227 227 247", // #e3e3f7
		"--color-secondary-100": "218 218 245", // #dadaf5
		"--color-secondary-200": "209 209 242", // #d1d1f2
		"--color-secondary-300": "181 181 235", // #b5b5eb
		"--color-secondary-400": "126 126 219", // #7e7edb
		"--color-secondary-500": "71 71 204", // #4747cc
		"--color-secondary-600": "64 64 184", // #4040b8
		"--color-secondary-700": "53 53 153", // #353599
		"--color-secondary-800": "43 43 122", // #2b2b7a
		"--color-secondary-900": "35 35 100", // #232364
		// tertiary | #33ccca
		"--color-tertiary-50": "224 247 247", // #e0f7f7
		"--color-tertiary-100": "214 245 244", // #d6f5f4
		"--color-tertiary-200": "204 242 242", // #ccf2f2
		"--color-tertiary-300": "173 235 234", // #adebea
		"--color-tertiary-400": "112 219 218", // #70dbda
		"--color-tertiary-500": "51 204 202", // #33ccca
		"--color-tertiary-600": "46 184 182", // #2eb8b6
		"--color-tertiary-700": "38 153 152", // #269998
		"--color-tertiary-800": "31 122 121", // #1f7a79
		"--color-tertiary-900": "25 100 99", // #196463
		// success | #33cc7f
		"--color-success-50": "224 247 236", // #e0f7ec
		"--color-success-100": "214 245 229", // #d6f5e5
		"--color-success-200": "204 242 223", // #ccf2df
		"--color-success-300": "173 235 204", // #adebcc
		"--color-success-400": "112 219 165", // #70dba5
		"--color-success-500": "51 204 127", // #33cc7f
		"--color-success-600": "46 184 114", // #2eb872
		"--color-success-700": "38 153 95", // #26995f
		"--color-success-800": "31 122 76", // #1f7a4c
		"--color-success-900": "25 100 62", // #19643e
		// warning | #f2b700
		"--color-warning-50": "253 244 217", // #fdf4d9
		"--color-warning-100": "252 241 204", // #fcf1cc
		"--color-warning-200": "252 237 191", // #fcedbf
		"--color-warning-300": "250 226 153", // #fae299
		"--color-warning-400": "246 205 77", // #f6cd4d
		"--color-warning-500": "242 183 0", // #f2b700
		"--color-warning-600": "218 165 0", // #daa500
		"--color-warning-700": "182 137 0", // #b68900
		"--color-warning-800": "145 110 0", // #916e00
		"--color-warning-900": "119 90 0", // #775a00
		// error | #cc333e
		"--color-error-50": "247 224 226", // #f7e0e2
		"--color-error-100": "245 214 216", // #f5d6d8
		"--color-error-200": "242 204 207", // #f2cccf
		"--color-error-300": "235 173 178", // #ebadb2
		"--color-error-400": "219 112 120", // #db7078
		"--color-error-500": "204 51 62", // #cc333e
		"--color-error-600": "184 46 56", // #b82e38
		"--color-error-700": "153 38 47", // #99262f
		"--color-error-800": "122 31 37", // #7a1f25
		"--color-error-900": "100 25 30", // #64191e
		// surface | #5a678b
		"--color-surface-50": "230 232 238", // #e6e8ee
		"--color-surface-100": "222 225 232", // #dee1e8
		"--color-surface-200": "214 217 226", // #d6d9e2
		"--color-surface-300": "189 194 209", // #bdc2d1
		"--color-surface-400": "140 149 174", // #8c95ae
		"--color-surface-500": "90 103 139", // #5a678b
		"--color-surface-600": "81 93 125", // #515d7d
		"--color-surface-700": "68 77 104", // #444d68
		"--color-surface-800": "54 62 83", // #363e53
		"--color-surface-900": "44 50 68", // #2c3244
	},
};
